FromOpenXliff2.1=Wrong XLIFF version
FromOpenXliff2.2=Error merging XLIFF 2.x skeleton
ToOpenXliff2.1=Wrong XLIFF version
ToOpenXliff2.2=Missing 'file' elements
ToOpenXliff2.3=Error generating XLIFF 2.x
